<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\Filament\ArticlesPanelProvider::class,
    App\Providers\Filament\BanquePanelProvider::class,
    App\Providers\Filament\ChantierPanelProvider::class,
    App\Providers\Filament\CommercePanelProvider::class,
    App\Providers\Filament\CorePanelProvider::class,
    App\Providers\Filament\CustomerPanelProvider::class,
    App\Providers\Filament\FlottesPanelProvider::class,
    App\Providers\Filament\GpaoPanelProvider::class,
    App\Providers\Filament\ImmobilisationPanelProvider::class,
    App\Providers\Filament\InterventionsPanelProvider::class,
    App\Providers\Filament\LocationsPanelProvider::class,
    App\Providers\Filament\PaiePanelProvider::class,
    App\Providers\Filament\RHPanelProvider::class,
    App\Providers\Filament\SalariePanelProvider::class,
    App\Providers\Filament\SubcontractorPanelProvider::class,
    App\Providers\Filament\TechnicienPanelProvider::class,
    App\Providers\Filament\TerrainPanelProvider::class,
    App\Providers\Filament\TiersPanelProvider::class,
    App\Providers\Filament\Vision3DPanelProvider::class,
    App\Providers\Filament\DocsPanelProvider::class,
    App\Providers\FortifyServiceProvider::class,
];
