import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Precache resources generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache API requests with Background Sync for offline support
const bgSyncPlugin = new BackgroundSyncPlugin('terrain-sync-queue', {
    maxRetentionTime: 24 * 60, // 24 hours
});

registerRoute(
    ({ url }) => url.pathname.startsWith('/api/journal/'),
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    }),
    'POST'
);

registerRoute(
    ({ url }) => url.pathname.startsWith('/api/etat-des-lieux/'),
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    }),
    'POST'
);

registerRoute(
    ({ url }) => url.pathname.startsWith('/api/reserves/'),
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    }),
    'POST'
);

// Cache pages navigation (NetworkFirst with fallback)
const navigationRoute = new NavigationRoute(
    new NetworkFirst({
        cacheName: 'pages',
        matchOptions: {
            ignoreSearch: true,
        },
        plugins: [
            {
                cacheDidUpdate: async ({ cache, request }) => {
                    // Notify clients when a page is updated in cache
                    const clients = await self.clients.matchAll();
                    clients.forEach(client => {
                        client.postMessage({
                            type: 'PAGE_CACHED',
                            url: request.url,
                        });
                    });
                },
            },
        ],
    })
);
registerRoute(navigationRoute);

// Cache assets (CSS, JS, Fonts) (CacheFirst with network fallback)
registerRoute(
    ({ request }) => ['style', 'script', 'font'].includes(request.destination),
    new CacheFirst({
        cacheName: 'assets',
    })
);

// Cache images (StaleWhileRevalidate for fresh content)
registerRoute(
    ({ request }) => request.destination === 'image',
    new StaleWhileRevalidate({
        cacheName: 'images',
    })
);

// Web-Push notifications logic
self.addEventListener('push', function (e) {
    if (!(self.Notification && self.Notification.permission === 'granted')) {
        return;
    }

    if (e.data) {
        let msg = e.data.json();
        e.waitUntil(self.registration.showNotification(msg.title, {
            body: msg.body,
            icon: msg.icon || '/favicon.ico',
            data: msg.data || {},
        }));
    }
});

self.addEventListener('notificationclick', function (event) {
    event.notification.close();

    const targetUrl = event.notification.data?.url || '/';

    event.waitUntil(
        clients.matchAll({ type: 'window' }).then(windowClients => {
            for (var i = 0; i < windowClients.length; i++) {
                var client = windowClients[i];
                if (client.url === targetUrl && 'focus' in client) {
                    return client.focus();
                }
            }
            if (clients.openWindow) {
                return clients.openWindow(targetUrl);
            }
        })
    );
});

// Handle messages from clients
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
