<?php

namespace Database\Seeders\Accounting;

use App\Models\Accounting\CompteComptable;
use Illuminate\Database\Seeder;

class PcgSeeder extends Seeder
{
    public function run(): void
    {
        $accounts = [
            // ===== CLASSE 1 : COMPTES DE RESSOURCES DURABLES =====
            ['numero' => '101100', 'libelle' => 'Capital émis', 'classe' => 1, 'is_balance' => true],
            ['numero' => '101200', 'libelle' => 'Primes liées au capital émis', 'classe' => 1, 'is_balance' => true],
            ['numero' => '104100', 'libelle' => 'Report à nouveau', 'classe' => 1, 'is_balance' => true],
            ['numero' => '106100', 'libelle' => 'Résultat de l\'exercice', 'classe' => 1, 'is_balance' => true],
            ['numero' => '108100', 'libelle' => 'Compte de l\'exploitant', 'classe' => 1, 'is_balance' => true],
            ['numero' => '110000', 'libelle' => 'Apports non libérés', 'classe' => 1, 'is_balance' => true],
            ['numero' => '120000', 'libelle' => 'Écarts de conversion (actif)', 'classe' => 1, 'is_balance' => true],
            ['numero' => '130000', 'libelle' => 'Charges à répartir sur plusieurs exercices', 'classe' => 1, 'is_balance' => false],
            ['numero' => '150000', 'libelle' => 'Charges immobilisées', 'classe' => 1, 'is_balance' => false],

            // ===== CLASSE 2 : IMMOBILISATIONS =====
            ['numero' => '203100', 'libelle' => 'Concessions et droits similaires, brevets, licences', 'classe' => 2, 'is_balance' => false],
            ['numero' => '207000', 'libelle' => 'Logiciels informatiques', 'classe' => 2, 'is_balance' => false],
            ['numero' => '211000', 'libelle' => 'Terrains', 'classe' => 2, 'is_balance' => false],
            ['numero' => '213000', 'libelle' => 'Constructions', 'classe' => 2, 'is_balance' => false],
            ['numero' => '215000', 'libelle' => 'Installations techniques, matériel et outillage industriels', 'classe' => 2, 'is_balance' => false],
            ['numero' => '215100', 'libelle' => 'Matériel de transport', 'classe' => 2, 'is_balance' => false],
            ['numero' => '215400', 'libelle' => 'Matériel de bureau et mobilier', 'classe' => 2, 'is_balance' => false],
            ['numero' => '218100', 'libelle' => 'Cheptel', 'classe' => 2, 'is_balance' => false],
            ['numero' => '218200', 'libelle' => 'Immobilisations corporelles diverses', 'classe' => 2, 'is_balance' => false],
            ['numero' => '220000', 'libelle' => 'Immobilisations en concession', 'classe' => 2, 'is_balance' => false],
            ['numero' => '231000', 'libelle' => 'Immobilisations en concession', 'classe' => 2, 'is_balance' => false],
            ['numero' => '237000', 'libelle' => 'Avances et acomptes sur immobilisations corporelles', 'classe' => 2, 'is_balance' => false],
            ['numero' => '260000', 'libelle' => 'Prises de participation', 'classe' => 2, 'is_balance' => false],
            ['numero' => '261000', 'libelle' => 'Titres de participation', 'classe' => 2, 'is_balance' => false],
            ['numero' => '267000', 'libelle' => 'Autres immobilisations financières', 'classe' => 2, 'is_balance' => false],
            ['numero' => '268000', 'libelle' => 'Autres immobilisations financières', 'classe' => 2, 'is_balance' => false],
            ['numero' => '270000', 'libelle' => 'Prêts', 'classe' => 2, 'is_balance' => false],
            ['numero' => '273000', 'libelle' => 'Prêts', 'classe' => 2, 'is_balance' => false],
            ['numero' => '274000', 'libelle' => 'Prêts', 'classe' => 2, 'is_balance' => false],
            ['numero' => '276000', 'libelle' => 'Dépôts et cautionnements versés', 'classe' => 2, 'is_balance' => false],
            ['numero' => '277000', 'libelle' => 'Autres créances immobilisées', 'classe' => 2, 'is_balance' => false],
            ['numero' => '281100', 'libelle' => 'Dotations aux amortissements - Immobilisations incorporelles', 'classe' => 2, 'is_balance' => false],
            ['numero' => '281200', 'libelle' => 'Dotations aux amortissements - Terrains', 'classe' => 2, 'is_balance' => false],
            ['numero' => '281300', 'libelle' => 'Dotations aux amortissements - Constructions', 'classe' => 2, 'is_balance' => false],
            ['numero' => '281500', 'libelle' => 'Dotations aux amortissements - Matériel', 'classe' => 2, 'is_balance' => false],
            ['numero' => '281800', 'libelle' => 'Dotations aux amortissements - Autres immobilisations corporelles', 'classe' => 2, 'is_balance' => false],
            ['numero' => '282000', 'libelle' => 'Dotations aux amortissements - Immobilisations financières', 'classe' => 2, 'is_balance' => false],
            ['numero' => '290000', 'libelle' => 'Provisions pour dépréciations d\'immobilisations', 'classe' => 2, 'is_balance' => false],

            // ===== CLASSE 3 : STOCKS =====
            ['numero' => '310000', 'libelle' => 'Marchandises', 'classe' => 3, 'is_balance' => false],
            ['numero' => '320000', 'libelle' => 'Matières premières', 'classe' => 3, 'is_balance' => false],
            ['numero' => '340000', 'libelle' => 'Fournitures', 'classe' => 3, 'is_balance' => false],

            // ===== CLASSE 4 : TIERS =====
            ['numero' => '401100', 'libelle' => 'Fournisseurs - Achats', 'classe' => 4, 'is_balance' => true],
            ['numero' => '401600', 'libelle' => 'Fournisseurs - Factures à réceptionner', 'classe' => 4, 'is_balance' => true],
            ['numero' => '401700', 'libelle' => 'Fournisseurs - Avances et acomptes', 'classe' => 4, 'is_balance' => true],
            ['numero' => '403100', 'libelle' => 'Fournisseurs - Lettres de change à payer', 'classe' => 4, 'is_balance' => true],
            ['numero' => '404000', 'libelle' => 'Fournisseurs - Retenues de garantie', 'classe' => 4, 'is_balance' => true],
            ['numero' => '408100', 'libelle' => 'Fournisseurs - Factures non parvenues', 'classe' => 4, 'is_balance' => true],
            ['numero' => '408200', 'libelle' => 'Fournisseurs - Charges à payer', 'classe' => 4, 'is_balance' => true],
            ['numero' => '408400', 'libelle' => 'Fournisseurs - Portefeuille d\'escomptes à payer', 'classe' => 4, 'is_balance' => true],
            ['numero' => '408700', 'libelle' => 'Fournisseurs - Divers', 'classe' => 4, 'is_balance' => true],
            ['numero' => '409100', 'libelle' => 'Contrepartie des amortissements provisions', 'classe' => 4, 'is_balance' => true],
            ['numero' => '411100', 'libelle' => 'Clients - Ventes de marchandises', 'classe' => 4, 'is_balance' => true],
            ['numero' => '411200', 'libelle' => 'Clients - Ventes de biens ou services', 'classe' => 4, 'is_balance' => true],
            ['numero' => '413100', 'libelle' => 'Clients - Lettres de change à recevoir', 'classe' => 4, 'is_balance' => true],
            ['numero' => '416000', 'libelle' => 'Clients - Retenues de garantie', 'classe' => 4, 'is_balance' => true],
            ['numero' => '417000', 'libelle' => 'Clients - Avances et acomptes', 'classe' => 4, 'is_balance' => true],
            ['numero' => '418100', 'libelle' => 'Clients - Factures à émettre', 'classe' => 4, 'is_balance' => true],
            ['numero' => '418200', 'libelle' => 'Clients - Produits à recevoir', 'classe' => 4, 'is_balance' => true],
            ['numero' => '418400', 'libelle' => 'Clients - Portefeuille d\'escomptes', 'classe' => 4, 'is_balance' => true],
            ['numero' => '418700', 'libelle' => 'Clients - Divers', 'classe' => 4, 'is_balance' => true],
            ['numero' => '419100', 'libelle' => 'Contrepartie des amortissements provisions', 'classe' => 4, 'is_balance' => true],
            ['numero' => '421000', 'libelle' => 'Personnel - Rémunérations dues', 'classe' => 4, 'is_balance' => true],
            ['numero' => '422000', 'libelle' => 'Personnel - Comité d\'entreprise', 'classe' => 4, 'is_balance' => true],
            ['numero' => '423000', 'libelle' => 'Personnel - Participation des salariés aux résultats', 'classe' => 4, 'is_balance' => true],
            ['numero' => '424000', 'libelle' => 'Personnel - Avances et acomptes', 'classe' => 4, 'is_balance' => true],
            ['numero' => '425000', 'libelle' => 'Personnel - Avances et acomptes', 'classe' => 4, 'is_balance' => true],
            ['numero' => '427000', 'libelle' => 'Personnel - Divers', 'classe' => 4, 'is_balance' => true],
            ['numero' => '431000', 'libelle' => 'Sécurité sociale et organismes sociaux', 'classe' => 4, 'is_balance' => true],
            ['numero' => '437000', 'libelle' => 'Autres organismes sociaux', 'classe' => 4, 'is_balance' => true],
            ['numero' => '441000', 'libelle' => 'État - Subventions à recevoir', 'classe' => 4, 'is_balance' => true],
            ['numero' => '442100', 'libelle' => 'Prélèvement à la source (PAS)', 'classe' => 4, 'is_balance' => true],
            ['numero' => '442600', 'libelle' => 'TVA collectée', 'classe' => 4, 'is_balance' => true],
            ['numero' => '442700', 'libelle' => 'TVA à décaisser', 'classe' => 4, 'is_balance' => true],
            ['numero' => '443100', 'libelle' => 'TVA sur immobilisations à décaisser', 'classe' => 4, 'is_balance' => true],
            ['numero' => '444000', 'libelle' => 'État - Impôts et taxes recouvrables sur des tiers', 'classe' => 4, 'is_balance' => true],
            ['numero' => '445200', 'libelle' => 'État - Taxes sur le chiffre d\'affaires - Constats', 'classe' => 4, 'is_balance' => true],
            ['numero' => '445600', 'libelle' => 'TVA déductible', 'classe' => 4, 'is_balance' => true],
            ['numero' => '445660', 'libelle' => 'TVA déductible sur autres biens et services', 'classe' => 4, 'is_balance' => true],
            ['numero' => '445710', 'libelle' => 'TVA récupérable d\'avance', 'classe' => 4, 'is_balance' => true],
            ['numero' => '445800', 'libelle' => 'État - Taxes sur le chiffre d\'affaires', 'classe' => 4, 'is_balance' => true],
            ['numero' => '455100', 'libelle' => 'Associés - Opérations sur le capital', 'classe' => 4, 'is_balance' => true],
            ['numero' => '456000', 'libelle' => 'Groupe - Opérations intercurrentes', 'classe' => 4, 'is_balance' => true],
            ['numero' => '457000', 'libelle' => 'Autres débiteurs et créditeurs', 'classe' => 4, 'is_balance' => true],

            // ===== CLASSE 5 : FINANCIER =====
            ['numero' => '512000', 'libelle' => 'Banque', 'classe' => 5, 'is_balance' => true],
            ['numero' => '512100', 'libelle' => 'Banque - Compte courant', 'classe' => 5, 'is_balance' => true],
            ['numero' => '512200', 'libelle' => 'Banque - Compte d\'épargne', 'classe' => 5, 'is_balance' => true],
            ['numero' => '512300', 'libelle' => 'Banque - Carte de crédit', 'classe' => 5, 'is_balance' => true],
            ['numero' => '516000', 'libelle' => 'Instruments financiers dérivés', 'classe' => 5, 'is_balance' => true],
            ['numero' => '522000', 'libelle' => 'Valeurs à encaisser', 'classe' => 5, 'is_balance' => true],
            ['numero' => '531000', 'libelle' => 'Caisse', 'classe' => 5, 'is_balance' => true],
            ['numero' => '540000', 'libelle' => 'Régies d\'accises et loterie', 'classe' => 5, 'is_balance' => true],
            ['numero' => '580000', 'libelle' => 'Virements internes', 'classe' => 5, 'is_balance' => true],

            // ===== CLASSE 6 : CHARGES =====
            ['numero' => '601100', 'libelle' => 'Achats de marchandises', 'classe' => 6, 'is_balance' => false],
            ['numero' => '602000', 'libelle' => 'Achats de matières premières', 'classe' => 6, 'is_balance' => false],
            ['numero' => '604000', 'libelle' => 'Achats de fournitures', 'classe' => 6, 'is_balance' => false],
            ['numero' => '605100', 'libelle' => 'Fournitures non stockées - Eau', 'classe' => 6, 'is_balance' => false],
            ['numero' => '605200', 'libelle' => 'Fournitures non stockées - Énergie', 'classe' => 6, 'is_balance' => false],
            ['numero' => '605400', 'libelle' => 'Fournitures de bureau', 'classe' => 6, 'is_balance' => false],
            ['numero' => '606000', 'libelle' => 'Autres matières et fournitures', 'classe' => 6, 'is_balance' => false],
            ['numero' => '607000', 'libelle' => 'Achats stockés (variation stock)', 'classe' => 6, 'is_balance' => false],
            ['numero' => '610000', 'libelle' => 'Services extérieurs', 'classe' => 6, 'is_balance' => false],
            ['numero' => '613000', 'libelle' => 'Locations', 'classe' => 6, 'is_balance' => false],
            ['numero' => '613500', 'libelle' => 'Locations - Matériel', 'classe' => 6, 'is_balance' => false],
            ['numero' => '613600', 'libelle' => 'Locations - Bâtiments', 'classe' => 6, 'is_balance' => false],
            ['numero' => '613700', 'libelle' => 'Locations - Véhicules', 'classe' => 6, 'is_balance' => false],
            ['numero' => '613800', 'libelle' => 'Locations - Matériel et outillage', 'classe' => 6, 'is_balance' => false],
            ['numero' => '621000', 'libelle' => 'Personnel extérieur à l\'entreprise', 'classe' => 6, 'is_balance' => false],
            ['numero' => '622100', 'libelle' => 'Rémunération d\'intermédiaires et honoraires', 'classe' => 6, 'is_balance' => false],
            ['numero' => '622600', 'libelle' => 'Honoraires', 'classe' => 6, 'is_balance' => false],
            ['numero' => '622700', 'libelle' => 'Frais d\'actes et de contentieux', 'classe' => 6, 'is_balance' => false],
            ['numero' => '622800', 'libelle' => 'Publicité, publications et relations publiques', 'classe' => 6, 'is_balance' => false],
            ['numero' => '623000', 'libelle' => 'Déplacements, missions et réceptions', 'classe' => 6, 'is_balance' => false],
            ['numero' => '624000', 'libelle' => 'Frais postaux et frais de télécommunications', 'classe' => 6, 'is_balance' => false],
            ['numero' => '625000', 'libelle' => 'Services bancaires', 'classe' => 6, 'is_balance' => false],
            ['numero' => '627000', 'libelle' => 'Autres services extérieurs', 'classe' => 6, 'is_balance' => false],
            ['numero' => '631000', 'libelle' => 'Impôts et taxes', 'classe' => 6, 'is_balance' => false],
            ['numero' => '631100', 'libelle' => 'Impôts et taxes directs', 'classe' => 6, 'is_balance' => false],
            ['numero' => '631200', 'libelle' => 'Impôts et taxes indirects', 'classe' => 6, 'is_balance' => false],
            ['numero' => '641100', 'libelle' => 'Salaires, appointements', 'classe' => 6, 'is_balance' => false],
            ['numero' => '641200', 'libelle' => 'Congés payés', 'classe' => 6, 'is_balance' => false],
            ['numero' => '641300', 'libelle' => 'Primes et gratifications', 'classe' => 6, 'is_balance' => false],
            ['numero' => '641400', 'libelle' => 'Indemnités et avantages divers', 'classe' => 6, 'is_balance' => false],
            ['numero' => '645000', 'libelle' => 'Charges sociales', 'classe' => 6, 'is_balance' => false],
            ['numero' => '645100', 'libelle' => 'Cotisations à la sécurité sociale', 'classe' => 6, 'is_balance' => false],
            ['numero' => '645200', 'libelle' => 'Cotisations aux mutuelles', 'classe' => 6, 'is_balance' => false],
            ['numero' => '645300', 'libelle' => 'Cotisations prévoyance', 'classe' => 6, 'is_balance' => false],
            ['numero' => '651000', 'libelle' => 'Rémunération du personnel', 'classe' => 6, 'is_balance' => false],
            ['numero' => '658000', 'libelle' => 'Autres charges de personnel', 'classe' => 6, 'is_balance' => false],
            ['numero' => '661000', 'libelle' => 'Charges financières', 'classe' => 6, 'is_balance' => false],
            ['numero' => '661100', 'libelle' => 'Charges d\'intérêts', 'classe' => 6, 'is_balance' => false],
            ['numero' => '661600', 'libelle' => 'Pertes de change', 'classe' => 6, 'is_balance' => false],
            ['numero' => '671000', 'libelle' => 'Autres charges opérationnelles', 'classe' => 6, 'is_balance' => false],
            ['numero' => '681100', 'libelle' => 'Dotations aux amortissements - Immobilisations', 'classe' => 6, 'is_balance' => false],
            ['numero' => '681200', 'libelle' => 'Dotations aux amortissements - Immobilisations en concession', 'classe' => 6, 'is_balance' => false],
            ['numero' => '686100', 'libelle' => 'Dotations aux provisions pour dépréciations - Immobilisations', 'classe' => 6, 'is_balance' => false],
            ['numero' => '686200', 'libelle' => 'Dotations aux provisions pour dépréciations - Actif circulant', 'classe' => 6, 'is_balance' => false],
            ['numero' => '686300', 'libelle' => 'Dotations aux provisions financières', 'classe' => 6, 'is_balance' => false],
            ['numero' => '686800', 'libelle' => 'Dotations aux provisions pour risques et charges', 'classe' => 6, 'is_balance' => false],
            ['numero' => '691000', 'libelle' => 'Impôts sur les bénéfices', 'classe' => 6, 'is_balance' => false],
            ['numero' => '695000', 'libelle' => 'Autres impôts sur les bénéfices', 'classe' => 6, 'is_balance' => false],

            // ===== CLASSE 7 : PRODUITS =====
            ['numero' => '701100', 'libelle' => 'Ventes de marchandises', 'classe' => 7, 'is_balance' => false],
            ['numero' => '701200', 'libelle' => 'Ventes de biens ou services', 'classe' => 7, 'is_balance' => false],
            ['numero' => '704000', 'libelle' => 'Chiffre d\'affaires', 'classe' => 7, 'is_balance' => false],
            ['numero' => '706000', 'libelle' => 'Rabais, remises et ristournes accordés', 'classe' => 7, 'is_balance' => false],
            ['numero' => '707000', 'libelle' => 'Produits accessoires', 'classe' => 7, 'is_balance' => false],
            ['numero' => '712000', 'libelle' => 'Variation de stocks de marchandises', 'classe' => 7, 'is_balance' => false],
            ['numero' => '713000', 'libelle' => 'Variation de stocks de matières premières', 'classe' => 7, 'is_balance' => false],
            ['numero' => '721000', 'libelle' => 'Production stockée', 'classe' => 7, 'is_balance' => false],
            ['numero' => '731000', 'libelle' => 'Production immobilisée', 'classe' => 7, 'is_balance' => false],
            ['numero' => '741000', 'libelle' => 'Subventions d\'exploitation', 'classe' => 7, 'is_balance' => false],
            ['numero' => '751000', 'libelle' => 'Autres produits d\'exploitation', 'classe' => 7, 'is_balance' => false],
            ['numero' => '761000', 'libelle' => 'Produits financiers', 'classe' => 7, 'is_balance' => false],
            ['numero' => '771000', 'libelle' => 'Autres produits', 'classe' => 7, 'is_balance' => false],

            // ===== CLASSE 8 : RÉSULTAT =====
            ['numero' => '880000', 'libelle' => 'Report à nouveau', 'classe' => 8, 'is_balance' => true],
            ['numero' => '890000', 'libelle' => 'Résultat de l\'exercice', 'classe' => 8, 'is_balance' => true],
        ];

        foreach ($accounts as $account) {
            CompteComptable::updateOrCreate(
                ['numero' => $account['numero']],
                $account
            );
        }
    }
}
